spring.application.name=crawl-qeecc-data
server.port=8086

# 目标网站
qeecc.site.base-url=http://www.qeecc.com

# 本地存储根路径
qeecc.local.store-path=/Volumes/files/my/qeecc

# 爬虫配置
qeecc.crawl.request-interval-ms=2000
qeecc.crawl.cookie-refresh-minutes=50
qeecc.crawl.max-concurrent-downloads=3
